site_name: Monday Night Bytes
nav:
  - Home: index.md
  - Contact: contact.md
  - Timetable: timetable.md
  - Links: links.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico

extra_css:
  - assets/css/neoteroi-timeline.css
  - assets/css/neoteroi-cards.css

markdown_extensions:
  - neoteroi.timeline
  - neoteroi.cards