# This is a basic workflow to help you get started with Actions

name: Build website

# Controls when the action will run.
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"   # Everyday at 061:00  https://crontab.guru/#0_6_*_*_*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r req.txt
          
      - name: Configure Git
        run: |
          git config user.name "Publisher"
          git config user.email "publisher@users.noreply.github.com"

      - name: Switch to branch 'gh-pages'
        run: |
          git branch -f gh-pages HEAD
          git checkout gh-pages

      - name: Generate HTML
        run: |
          python get_timetable.py
          mkdocs build -d public

      - name: Save commit hash to file
        run: git rev-parse --short HEAD > public/commithash.txt

      - run: |
          git add -A
          git add -f public
          git commit -m "Publish"
          git push -f origin `git subtree split -P public`:refs/heads/gh-pages